### ISSUE TITLE
DSN module with jakarta-mail bundle module issue (2)

### ISSUE THREAD

**Issue by jbescos** [eclipse-ee4j/angus-mail#32]
Current DSN module contains the next module-info.java:

```
module com.sun.mail.dsn {

    requires com.sun.mail;

    exports com.sun.mail.dsn;
}
```

The issue is that DSN could be in module-path together with jakarta-mail bundle. Jakarta-bundle has different module name, that is `jakarta.mail` instead of `com.sun.mail`.

Proposed solution:

DSN module should work with both modules.

Related issue: https://github.com/eclipse-ee4j/angus-mail/issues/29

**Comment by PeteSL** [comment]
I confirm that the bundle acts as jakarta.mail 2.0 using the jakarta.mail module name. Angus mail moved all com.sun.mail packages to a new module, com.sun.mail.  I have not tested but expect that if you used dsn-2.0.1.jar with jakarta.mail-1.0.0.jar, it would work since DSN 2.0.1 would require jakarta.mail, not com.sun.mail.

Because of the divergence of 2.1.0 (and future releases) from prior versions with a new module for implementation, I recommend that you do not alter DSN as you can't make it not require the com.sun.mail module since it makes direct calls to com.sun.mail packages and do one of 2 things:

1. Make an implementation note for DSN, GIMAP, etc. that they require the unbundled versions of jakarta.mail/angus-mail and do not support the bundled version.
2. Don't make a bundled version anymore as but it must be called out in the API and in implementations notes that com.sun.mail packages are no longer included in the jakarta.mail API and for an application to be compatible with both 2.0.1 and newer versions, the command line argument --add-reads app.module.name=com.sun.mail must be added so the existing application module(s) that make direct calls to the com.sun.mail packages (com.sun.mail.imap being the most probable package) can continue to operate as before.

I do not think that the proposed solution is doable as you would either get the error we would see in 2 above if the requires com.sun.mail were removed or you would get the error we see when using the bundle if the requires com.sun.mail is kept.

With Jakarta EE 10's migration to API/implementation architecture and with the decision to move all com.sun.mail packages to the com.sun.mail module, I recommend that 1 and/or 2 be used as the solution.

**Comment by jbescos** [comment]
@PeteSL it is possible to make DSN and GIMAP to work with both modules (`com.sun.mail` and `jakarta.mail`) with the `requires static`. That verifies DSN and GIMAP has access to the modules in runtime and it does not forces to have that 2 modules in modulepath.

I have opened a PR to fix these issues.
