### ISSUE TITLE
The link to the home page is broken and i cant find the new one

### ISSUE THREAD

**Issue by cowley05** [eclipse-ee4j/angus-mail#38]
**Describe the bug**
When click the link you have in the readme for the homepage it links to here: https://eclipse-ee4j.github.io/mail which is no longer there - see 404 screenshot. I cant find the actual link anywhere so cant get to the actual site.

**To Reproduce**
1. Go to the Readme shown [here](https://github.com/eclipse-ee4j/angus-mail)
2. Click on [Jakarta Mail Website](https://eclipse-ee4j.github.io/mail)
3. See error

**Expected behavior**
An actual website

**Screenshots**
![image](https://user-images.githubusercontent.com/1880175/198003929-0202fee3-b7e2-4901-a03b-e0ffaf76f32d.png)

**Comment by maeichris** [comment]
Note that the entire [eclipse-ee4j.github.io](https://eclipse-ee4j.github.io/) website appears to be down.

The link on the [downloads page of the project site](https://projects.eclipse.org/projects/ee4j.mail/downloads) is also broken due to the site being down.

This effectively leaves no way of finding where one can download JavaMail/JakartaMail/?ArgusMail? if one does not already know where it is.  This makes it look like the project has been abandoned.

**Comment by jbescos** [comment]
I had been moved here: https://github.com/jakartaee/mail-api

I will fix the link
